language: cpp
sudo: required
dist: bionic
compiler:
- clang
os:
- linux

before_install:
- which clang
- which cmake

script:
- mkdir -p build && cd build && cmake .. && make

notifications:
  email: false